Access-Point-Program/cohort-3-dashboard

- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/definition-of-ready.md
Added onto already made issue template
> Ready issue template 2

- src/app/app.component.html
- src/app/app.component.ts
- src/app/app.module.ts
- src/app/rulesets/rulesets.component.css
- src/app/rulesets/rulesets.component.html
- src/app/rulesets/rulesets.component.spec.ts
- src/app/rulesets/rulesets.component.ts
> hiiiiiiiiiii

- mock/data/layouts.json
- mock/layoutapi.js
- package.json
- src/app/Layouts.ts
- src/app/layouts.service.spec.ts
- src/app/layouts.service.ts
- src/app/table/table.component.html
- src/app/table/table.component.ts
created the end points for the layouts page and mock data as well.
Story #59 
user testing
> finale layout

- mock/api.js
- src/app/app.component.ts
- src/app/rulesets.service.ts
- src/app/rulesets/rulesets.component.css
- src/app/rulesets/rulesets.component.html
- src/app/rulesets/rulesets.component.ts
> This might break

- src/app/layouts.service.ts
- src/app/table/table.component.css
- src/app/table/table.component.html
- src/app/table/table.component.ts
[added functionality to layout mock api table]
Story #[61]
> delete button working for layouts

- src/app/rulesets/rulesets.component.css
- src/app/rulesets/rulesets.component.html
- src/app/table/table.component.css
- src/app/table/table.component.html
- src/app/table/table.component.ts
Pagination was messed up so I fixed it, and fixed buttons to look better. I also, made the edit img a button
User testing
> fix buttons and small bug

- src/app/rulesets/rulesets.component.html
- src/app/rulesets/rulesets.component.ts
- src/app/table/table.component.html
- src/app/table/table.component.ts
Shouldn't bring up any page. It should actually bring up an error page
Story #57 
User testing
> edit button created

- mock/data/layouts.json
- mock/data/rulesets.json
- src/app/Layouts.ts
- src/app/table/table.component.html
- src/main/java/com/example/dashboard/controllers/LayoutController.java
- src/main/java/com/example/dashboard/models/Layout.java
- src/main/java/com/example/dashboard/services/LayoutService.java
- src/test/java/com/example/dashboard/LayoutControllerTests.java
implement the endpoints for delete and get
Story #56 
##How to run
open project in intellij
open 3 separate terminals in gitbash  for ng serve --open,(use cd mock then  npm run mock:rulesets, and npm run mock:layouts
run the springboot DashboardApplication file in cohort-3-dashboard\src\main\java\com\example\dashboard
open postman and use the link http://localhost:9030/layout to test the get endpoint and use  http://localhost:9030/layout/1 for the delete endpoint
Do the exact same thing for rulesets but change layout to ruleset
rest assured
> Layout get and delete api

- package-lock.json
- src/app/rulesets/rulesets.component.ts
- src/app/table/table.component.ts
Just added id for edit button for presentation
also updated npm
> added some things for presentation

- src/app/app.component.css
- src/app/rulesets/rulesets.component.css
- src/app/rulesets/rulesets.component.html
I made the create ruleset button on the ruleset page
Story #54 
user
> ruleset create button completed

- src/app/rulesets/rulesets.component.html
- src/app/rulesets/rulesets.component.ts
- src/app/sidebar/sidebar.component.html
- src/app/table/table.component.html
- src/app/table/table.component.ts
Set up routes for buttons with the information that was provided. We will most likely have to do some tweaks when we actually connect as we don't have all the info.
Story #74 
User
> routes set up and ready

- src/app/rulesets/rulesets.component.css
- src/app/table/table.component.css
There was some extra space at the bottom of the page. I removed some padding to make it fit.
User
> removed blank space at bottom

- src/test/java/com/example/dashboard/LayoutControllerTests.java
- src/test/java/com/example/dashboard/RuleSetsControllerTests.java
Added deletion tests for api
rest assured
> added deletion tests for api

- src/app/rulesets/rulesets.component.css
- src/app/rulesets/rulesets.component.html
- src/app/rulesets/rulesets.component.ts
- src/app/sidebar/sidebar.component.html
- src/app/table/table.component.css
- src/app/table/table.component.html
- src/app/table/table.component.ts
Added confirmation box on delete button
User
> added confirmation on delete button

- src/app/rulesets/rulesets.component.html
- src/app/rulesets/rulesets.component.ts
- src/main/java/com/example/dashboard/DashboardApplication.java
- src/main/java/com/example/dashboard/configuration/RestConfiguration.java
spring and url fix/update
ran everything and tested the reload
> spring and url fix/update

- src/app/table/table.component.spec.ts
This commit adds tests for the layout table to make sure everything works. 
Using the spec files in the application
> Adding tests for layouts table

- package.json
- spec/support/jasmine.json
- src/app/app.component.spec.ts
- src/app/app.module.ts
- src/app/rulesets/rulesets.component.spec.ts
- src/app/sidebar/sidebar.component.spec.ts
Added a bit of testing for ruleset table though I could not figure out how to test routing to a localhost
Jasmine
> added testing for ruleset table

- mock/data/layouts.json
- src/app/rulesets/rulesets.component.css
- src/app/rulesets/rulesets.component.html
- src/app/table/table.component.css
- src/app/table/table.component.html
- src/main/java/com/example/dashboard/services/LayoutService.java
> fixed table

- package-lock.json
- src/app/app.component.spec.ts
> Appcomponenttest

- src/app/sidebar/sidebar.component.html
> Fixed sidebar for Cyclones

- src/test/java/com/example/dashboard/LayoutControllerTests.java
- src/test/java/com/example/dashboard/RuleSetsControllerTests.java
added testing to the api 
ran with test coverage
> rest assured testing

- src/app/Ruleset.ts
- src/app/rulesets/rulesets.component.html
- src/app/rulesets/rulesets.component.ts
- src/main/java/com/example/dashboard/models/RuleSet.java
> Ruleset dates works
